### ISSUE TITLE
Missing CSS file

### ISSUE THREAD

**Issue by vsvetoslavov** [Ksena19/tipCalculator#1]
The page _tipCalculator.html_ refers non-existent CSS resource _css/tipCalculator.css_

Here is a sample CSS file you can use

```css
/* background of page */
body {
	padding: 40px;
	padding-top: 10px;
	background-image: url('https://pulsefit.bg/uploads/cache/original/public/uploads/media-manager/app-modules-extras-models-extra/header/11/761/restorant.jpg');
	background-repeat: no-repeat;
	background-size: cover;
}
/* title */
h1 {
	text-shadow: 0 0 5px #ffe439;
	background: linear-gradient(0deg, #fbd023 0%, #fef757 30%, #f4dc20 60%, #fece31 100%);
	background-clip: text;
	-webkit-text-fill-color: transparent;
	outline: 10px green;
}
/* form */
form#calc {
  position: absolute;
  border: 2px solid rgb(64, 2, 0);
  padding: 20px;
  background: linear-gradient(120deg, rgba(64, 2, 0,0.3) 0%, rgba(64, 2, 0,0.4) 100%);
  border-radius: 15px;
  box-shadow: 0 0 5px rgb(64, 2, 0);
  color: #ffe439;
}

/* hide some line breaks */
br:first-of-type, br:nth-of-type(3) {
  display: none
}

/* form controls, labels, etc */

form#calc input {
  width: 300px;
  border: 2px solid rgba(251, 225, 47, 0.64);
  padding: 5px;
  border-radius: 5px;
  background: rgba(251, 225, 47, 0.64);
  color: rgb(64, 2, 0);
  display: block;
  margin-bottom: 10px;
}
form#calc label {
  width: 200px;
  display: inline-block;
  padding-bottom: 10px;
}

form#calc input#tip, form#calc input#total {
  background: rgba(64, 2, 0,0.6);
  content: "do not edit";
  color: rgba(251, 225, 47, 0.64);
}
form#calc input[type="submit"] {
  background: rgba(64, 2, 0,0.6);
  border: 2px solid rgba(64, 2, 0,0.6);
  border-radius: 5px;
  padding: 8px;
  font: message-box;
  color: #ffe439;
  width: auto;
  margin-top: 10px;
  float: right;
  outline: 10, 10, darkblue;
}
form#calc input[type="submit"]:hover {
  background: rgba(64, 2, 0,1);
}
```
